name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega cuando haya un push a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Asegúrate de usar una versión compatible

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}  # Aquí se inyecta tu API Key desde los secretos
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token para desplegar en GitHub Pages
          publish_dir: ./dist  # Directorio de salida del build
